name: Build ESP8266 BIN

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v2

    - name: Install ESP8266 core
      run: |
        arduino-cli core update-index
        arduino-cli core install esp8266:esp8266

    - name: Compile code
      run: |
        arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 .

    - name: Upload BIN
      uses: actions/upload-artifact@v4
      with:
        name: esp8266-bin
        path: build/*
